name: Deploy

on:
  workflow_run:
    workflows: ["Create and publish a Docker image"]
    branches: [main]
    types:
      - completed

jobs:
    deploy:
      name: Deploy bot
      runs-on: ubuntu-latest
      steps:
        - name: Remote deploy
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            key: ${{ secrets.SSH_KEY }}
            port: ${{ secrets.SSH_PORT }}
            script: |
              cd ~/projects/pythonista-api/
              git reset --hard HEAD || true
              git pull origin main
              docker compose pull
              docker compose up -d --build --force-recreate
            username: ${{ secrets.SSH_USER }}
